version: 0.0.2
config:
    project:
        name: AA
        version: 0.1.0
        context: devnet
        project_uuid: ac35c75d-6783-41e7-8f61-51c6fa8f64e2
        telemetry_enabled: false
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.0.13
